FROM 316263240806.dkr.ecr.ap-northeast-1.amazonaws.com/tesla/office

ADD ConvertQueueService.jar /opt/SyncQueue/
EXPOSE 8080
WORKDIR /opt/SyncQueue/
CMD ["java", "-Xms512m", "-Xmx1g", "-jar", "SyncQueue.jar"]
